services:
  warehousemanager-webhost:
    build:
      dockerfile: WarehouseManager.WebHost/Dockerfile
    restart: always
    ports:
      - "5580:8080"
    environment:
      - "ConnectionStrings:WareHouseManagerDb=Host=warehouse-manager-db;Port=5432;Database=WarehouseManagerDb;Username=postgres;Password=147258369"
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - warehouse-manager-db

  warehouse-manager-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=147258369
      - POSTGRES_USER=postgres
      - POSTGRES_DB=WarehouseManagerDb
    ports:
      - "5432:5432"
